# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 226e97e5994236c49c9666cf4e5ce05f19be6474ddb9a83a5c15fc8f1c2a15e94ad73805aab16dd4245fc141224d48948f7da20e42c8c8037422d86df24bcd26

test:
  secret_key_base: a1b15a16bad277adcc03f52a1bc891e0e39ddf27cddd56a0d12541ce226eb97d38541b9a252adc8ea74d2877cba1e46bab855d3327111dff65fe9483a895228e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
